apiJAVA: menuJava.o index_txt.o index_sound.o by_keyword.o pile.o image_main.o index_img.o
	gcc -o apiJAVA menuJava.o index_txt.o index_sound.o by_keyword.o pile.o image_main.o index_img.o

menuJava.o: menuJava.c ../INDEXATION/index_txt.c ../INDEXATION/index_sound.c  ../SEARCH/by_keyword.c ../INDEXATION/index_img.c  ../INDEXATION/image_main.c ../LIBS/IMAGE/pile.c
	gcc -c menuJava.c ../INDEXATION/index_txt.c ../INDEXATION/index_sound.c  ../SEARCH/by_keyword.c ../INDEXATION/index_img.c  ../INDEXATION/image_main.c ../LIBS/IMAGE/pile.c


